#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x ulauncher > /dev/null || ulauncher --hide-window --no-window-shadow &

bspc monitor -d 'Main' 'Code' 'Term' 'Web' 'Chat' '6' '7' '8' '9' '0'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#498391"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Enpass state=floating follow=on
bspc rule -a Chromium desktop='^4' follow=on
bspc rule -a firefox desktop='^4' follow=on
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a Alacritty desktop='^3' follow=on
bspc rule -a Slack desktop='^5'
bspc rule -a Spotify desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config external_rules_command "$HOME/.config/bspwm/bspwm-external-rules"

# Java application fix
wmname LG3D &

# wallpaper
feh --bg-fill $HOME/.config/bspwm/wallpaper.png

# status bar
$HOME/.config/polybar/launch.sh

# compositor
killall -q picom; picom --config $HOME/.config/picom/picom.conf &

# notification
killall -q dunst; dunst &

# session lock
xset s on
xset s 600 1
export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_SHOW_USERNAME=0
export XSECURELOCK_SHOW_DATETIME=0
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_PASSWORD_PROMPT=time_hex
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=1
export XSECURELOCK_FONT="Noto Sans CJK TC,Noto Sans CJK TC Medium:style=Medium,Regular"
export XSECURELOCK_DIM_TIME_MS=1000
killall -q xss-lock; xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# fcitx
fcitx &
