#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x ulauncher > /dev/null || ulauncher --hide-window --no-window-shadow &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# wallpaper
feh --bg-fill $HOME/.config/bspwm/wallpaper.png

# status bar
$HOME/.config/polybar/launch.sh

# compositor
killall -q picom; picom --config $HOME/.config/picom/picom.conf

# notification
killall -q dunst; dunst &

# session lock
xset s on
xset s 300 300
export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_SHOW_USERNAME=0
export XSECURELOCK_SHOW_DATETIME=0
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_PASSWORD_PROMPT=time_hex
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=1
export XSECURELOCK_FONT="Noto Sans CJK TC,Noto Sans CJK TC Medium:style=Medium,Regular"
export XSECURELOCK_DIM_TIME_MS=1000
killall -q xss-lock; xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
